language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

matrix:
    fast_finish: true


before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update

install:
    - composer install --prefer-source

script: ./bin/phpspec run --no-interaction
